package it.polimi.swimv2.enums;

public enum NotificationType {

	FRIENDSHIP_RECEIVED_DIRECT, FRIENDSHIP_RECEIVED, FRIENDSHIP_ACCEPTED_DIRECT, FRIENDSHIP_ACCEPTED, ABILITY_ACCCEPTED, ABILITY_REJECTED, ADMIN_PROMOTION, HELP_REJECTED;

}
